
   
question_data = [
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Humans and dinosaurs lived at the same time.", "answer": "False"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain on Earth.", "answer": "False"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Spiders are insects.", "answer": "False"},
    {"text": "Water boils faster at higher altitudes.", "answer": "False"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Humans share about 60% of their DNA with bananas.", "answer": "True"},
    {"text": "Adult humans have 206 bones.", "answer": "True"},
    {"text": "There are five different blood groups.", "answer": "False"},
    {"text": "Dogs sweat mainly through their paws.", "answer": "True"},
    {"text": "The human heart is located on the left side of the chest.", "answer": "False"},
    {"text": "Antarctica is the driest continent on Earth.", "answer": "True"},
    {"text": "Birds are reptiles.", "answer": "True"},
    {"text": "The tongue has different taste zones.", "answer": "False"},
    {"text": "Wearing headphones for long periods can damage hearing.", "answer": "True"},
    {"text": "Camels store water in their humps.", "answer": "False"},
    {"text": "The Eiffel Tower grows taller in summer.", "answer": "True"},
    {"text": "An adult human has more than five senses.", "answer": "True"},
    {"text": "Tomatoes are vegetables.", "answer": "False"},
    {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "There are 24 hours in a day everywhere on Earth.", "answer": "False"},
    {"text": "Pluto is classified as a planet.", "answer": "False"},
    {"text": "Some metals explode when exposed to water.", "answer": "True"},
    {"text": "The brain feels pain.", "answer": "False"},
    {"text": "Humans can breathe and swallow at the same time.", "answer": "False"},
    {"text": "Cows have best friends.", "answer": "True"},
    {"text": "The Moon produces its own light.", "answer": "False"},
    {"text": "There are more trees on Earth than stars in the Milky Way.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The human body is about 60% water.", "answer": "True"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Blood is blue inside the body.", "answer": "False"},
    {"text": "Some turtles can breathe through their butts.", "answer": "True"},
    {"text": "There are 1000 years in a millennium.", "answer": "True"},
    {"text": "A sneeze can travel faster than a car.", "answer": "True"},
    {"text": "Humans glow in the dark.", "answer": "True"},
    {"text": "All bacteria are harmful.", "answer": "False"},
    {"text": "Ice is heavier than water.", "answer": "False"},
    {"text": "The longest river in the world is the Nile.", "answer": "False"},
    {"text": "A cockroach can live without its head for days.", "answer": "True"},
    {"text": "You can taste food better when it is hot.", "answer": "False"},
    {"text": "The average human body temperature is 37°C.", "answer": "True"},
    {"text": "Chameleons change color to match their surroundings.", "answer": "False"},
    {"text": "Some fish can drown.", "answer": "True"},
    {"text": "There are 12 cranial nerves.", "answer": "True"},
    {"text": "Humans only use 10% of their brains.", "answer": "False"},
    {"text": "Glass is a supercooled liquid.", "answer": "False"},
    {"text": "Octopuses can taste with their suckers.", "answer": "True"},
    {"text": "The sun is a star.", "answer": "True"},
    {"text": "A full moon affects human behavior.", "answer": "False"},
    {"text": "Some frogs can freeze without dying.", "answer": "True"},
    {"text": "Sound cannot travel in a vacuum.", "answer": "True"},
    {"text": "Your hair and nails keep growing after death.", "answer": "False"},
    {"text": "There are more possible games of chess than atoms in the universe.", "answer": "True"},
    {"text": "You can see the Great Wall from the Moon.", "answer": "False"},
    {"text": "Humans can regenerate lost limbs.", "answer": "False"},
    {"text": "The human nose can detect over 1 trillion smells.", "answer": "True"},
    {"text": "Some clouds weigh more than a million tons.", "answer": "True"},
    {"text": "Fish can get seasick.", "answer": "True"},
    {"text": "There are 8 planets in the solar system.", "answer": "True"},
    {"text": "An adult human has 32 teeth.", "answer": "True"},
    {"text": "All mammals live on land.", "answer": "False"},
    {"text": "The human liver can regenerate itself.", "answer": "True"},
    {"text": "Plants can feel pain.", "answer": "False"},
    {"text": "Your stomach produces a new lining every few days.", "answer": "True"},
    {"text": "Some metals are liquid at room temperature.", "answer": "True"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "Snails can sleep for up to three years.", "answer": "True"},
    {"text": "You lose most of your body heat through your head.", "answer": "False"},
    {"text": "There are more insects than humans on Earth.", "answer": "True"},
    {"text": "Humans have a tailbone.", "answer": "True"},
    {"text": "The color of Coca-Cola is naturally green.", "answer": "False"},
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]